# Generated by Django 5.0 on 2023-12-19 10:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('musician', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MusiciansModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AlbumName', models.CharField(max_length=100)),
                ('date', models.DateField(max_length=100)),
                ('rating', models.CharField(max_length=2)),
                ('musician', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='musician.musiciansmodel')),
            ],
        ),
    ]
