# Generated by Django 5.0 on 2023-12-19 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0001_initial'),
        ('musician', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MusiciansModel',
            new_name='albumModel',
        ),
    ]
